### ISSUE TITLE
FRMS-coe-lib - remove channel feature

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/frms-coe-lib#94]
## User Story

**As a** Tazama system operator
**I want** to remove the channel feature
**so that** the system is as simple as possible to maintain and configure for an inexperienced user; and
**so that** the system performs as fast as possible at the lowest possible cost

**Impact assessment** required to determine if this repository is impacted by removing the channel feature (found in a search of code)

## Acceptance Criteria
1. Update the protobuf file encoding schema to remove the channel
2. Update the protobuf file encoding schema to remove the true/false distinction from the rule results
3. Update class definitions (models) for the configuration objects
4. Update class definitions (models) rule results and message payloads
5. Tests via integration testing
6. Push to dev branch/main branch and publish the package as a new release version in the main branch
7. Create/Update the documentation

**Comment by Justus-at-Tazama** [comment]
@scott45 - please explore a release/publish strategy for the library (supporting modules) - @Lenbkr suggested pre-release tags as an opportunity
